---
name: PermColors
version: 1.2
main: de.timmyrs.PermColors
author: timmyRS
website: https://timmyrs.de

commands:
  permcolors: {}

permissions:
  permcolors.chat:
    default: true
  permcolors.chat.color:
    children:
      permcolors.chat: true
  permcolors.*:
    default: 'op'
    children:
      permcolors.chat.color: true
      permcolors.reload: true
      permcolors.recolor: true
  # backward compatibility
  permcolors.colorfulchatmessages:
    children:
      permcolors.chat.color: true
